### ISSUE TITLE
Snap does not start on Ubuntu 19.04

### ISSUE THREAD

**Issue by onetransistor** [thomasnordquist/MQTT-Explorer#112]
After installing from Snap (version 0.2.5 appears in Ubuntu Software), when attempting to launch:

    [6779:0502/182042.490475:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /snap/mqtt-explorer/15/chrome-sandbox is owned by root and has mode 4755.
    Trace/breakpoint trap (core dumped)

That shouldn't be a big deal since one could use `chown` and `chmod` to set file owner and permissions. However, ["It's impossible to change the contents of the snap without re-building the snap"](https://askubuntu.com/a/919098/269282).

**Comment by thomasnordquist** [comment]
Thanks for reporting.
I'm onto it, in the meantime I rolled back snapcraft to 0.2.3.

This problem seems to be limited to snap packages. I'll keep you posted on the progress.

**Comment by thomasnordquist** [comment]
Snaps disallow suid flags in app reviews....
```
  - found errors in file output: unusual mode 'rwsr-xr-x' for entry './chrome-sandbox'
```

**Comment by thomasnordquist** [comment]
I fixed it in the current build and released a new snapcraft build. Since the build number is incremented all affected people should receive the patched release.

Keeping this issue open since there are still things to do:
- [ ] Check AppImage builds with different kernel options (see referenced issue)
- [ ] Disable the sandbox for future snap builds (rely on the snapd sandbox)
- [ ] Find better option then to modify the snap after it has been packaged.

**Comment by thomasnordquist** [comment]
Nasty issue since I only tested the AppImage/OSX/"Windows Installer" builds.
I should evaluate if it is possible to run automated ui-tests for all the downloadable formats.

You should be able to update with `sudo snap refresh mqtt-explorer`.

**Comment by onetransistor** [comment]
It is working now. Thank you!

**Comment by thomasnordquist** [comment]
Thank you for the quick bug-report 😉
