### ISSUE TITLE
About Application screen is blank

### ISSUE THREAD

**Issue by Peterkn2001** [thomasnordquist/MQTT-Explorer#115]
In v2.0.5 and v2.0.6 for Windows the Application >> About Application screen shows this image:

![image](https://user-images.githubusercontent.com/35718564/57238790-23015680-7022-11e9-8f03-1a73c92bf34c.png)
This makes it impossible to work-out which version of the app you're running.

Pete.

**Comment by thomasnordquist** [comment]
Thank you for reporting this.
I love to keep all my software components up-to-date so I have upgraded [Electron](https://github.com/electron/electron) from v4.1.3 to v5.0.0 and a lot of things broke during the upgrade. I tested the upgraded App extensively but it seems I have missed at least one thing 🤨.

Will be fixed with the next release.

**Comment by thomasnordquist** [comment]
Appears to be resolved with the latest electron version, will test this on a windows machine prior to the next release.

**Comment by thomasnordquist** [comment]
I verified, its working again after updating electron to 5.0.4.
<img width="401" alt="Bildschirmfoto 2019-06-19 um 08 57 20" src="https://user-images.githubusercontent.com/7721625/59743381-46016600-9270-11e9-8218-802163ef9a6a.png">
