### ISSUE TITLE
[Question] Keyboard shortcut to publish message?

### ISSUE THREAD

**Issue by felixstorm** [thomasnordquist/MQTT-Explorer#149]
Is there any keyboard shortcut to publish the current message? I could not find anything in the documentation / changelog, and the usual suspects (Ctrl-Enter etc.) do not seem to work...

Thanks,
Felix

**Comment by thomasnordquist** [comment]
Thank you for contributing.
You are indeed correct, the key binding was missing, I just very recently added keyboard support, and it is only released for Ubuntu, due to a bugfix release 😅.
Nice to see people already use it.

The feature has been added with https://github.com/thomasnordquist/MQTT-Explorer/commit/183ea9d8c0673d1c58c562a260ef8a8606ac656f.

I can't yet tell when the next release is due, there are still a few small things to do.

**Comment by felixstorm** [comment]
Great, thank you!

**Comment by thomasnordquist** [comment]
Released with [v0.3.5](https://github.com/thomasnordquist/MQTT-Explorer/releases/tag/v0.3.5).
