### ISSUE TITLE
Add Amazon MQTT support

### ISSUE THREAD

**Issue by thomasnordquist** [thomasnordquist/MQTT-Explorer#17]
Needs certificates, possibly a different mqtt lib.
(amazon examples ship with a working lib)

**Comment by TheRyanBurke** [comment]
Can you provide more details on this issue? I've validated the client can connect to AWS IoT Core with X.509 certs.

**Comment by thomasnordquist** [comment]
Client certificates now allow connecting to Amazon's IoT service but while testing it I experience disconnects due to missing permissions to subscribe with a wild card.
I don't have enough experience with Amazon's IoT platform to confirm it really works.
What is your experience so far?

**Comment by TheRyanBurke** [comment]
I tested with broad permissions applied to my certificate which allows publishing and subscribing on any topic (a `"Resource": "*"` policy in AWS terminology). This enabled me to connect and test pub/sub functionality with the client and another web client hosted in the AWS management console. There's a distinction in AWS policy definition between "subscribe to _any_ topic" (a resource like `"arn:aws:iot:REGION:ACCOUNT:topicfilter/*"`) and "subscribe to _the_ MQTT wildcard topic" (a resource like `"arn:aws:iot:REGION:ACCOUNT:topicfilter/#"`).

One note about using this client with AWS IoT Core is that broker does not permit subscribing to "$SYS" or any topic sub-space of "$SYS" such as "$SYS/#". The AWS IoT Core broker will disconnect clients trying to subscribe in this topic space. Because this is a default subscription in new connections from MQTT Explorer, it may yield a perception that this client and AWS IoT Core are incompatible. For future readers, drop the "$SYS/#" default subscription before connecting to AWS IoT Core.

**Comment by thomasnordquist** [comment]
Thanks for sharing 👍. I just might write a small introduction for it on https://mqtt-explorer.com next week.

**Comment by thomasnordquist** [comment]
Close since it is working, documentation is missing. #194
