### ISSUE TITLE
IPV6 not working

### ISSUE THREAD

**Issue by ronaldbenve** [thomasnordquist/MQTT-Explorer#193]
Hi, I tested IPV6 address with and without '[' ']', but not working.

**Comment by thomasnordquist** [comment]
I assume IPv6 (via host) works fine?

I'll look into it, thanks for reporting the issue!

**Comment by ronaldbenve** [comment]
Hi Thomas :

Yes, working with mqtt.fx

Best Regards

Ronald Benvenutti
Porto Alegre RS Brazil



Em sex, 2 de ago de 2019 às 11:31, Thomas Nordquist <
notifications@github.com> escreveu:

**Comment by thomasnordquist** [comment]
It seems to be working in general.
But I believe you cannot connect to local IPv6 addresses (`fe80::`), since the outgoing device needs to be specified but chrome/electron cannot understand the URL:

`fe80::10f0:207f:aead:8774%en0`
Connection to `fe80::10f0:207f:aead:8774` via `en0` interface

<img width="858" alt="Bildschirmfoto 2019-11-12 um 07 40 46" src="https://user-images.githubusercontent.com/7721625/68648073-c5dde480-051f-11ea-8489-3367d32236eb.png">
