### ISSUE TITLE
Wrong install location on Windows

### ISSUE THREAD

**Issue by kintrupf** [thomasnordquist/MQTT-Explorer#269]
Currently MQTT-Explorer tries to install to "C:\Users\<username>\AppData\Local\Programs\MQTT-Explorer", which is not a good choice. Since this is a user-writable location it should NOT contain executable code, which should only go to "C:\Program Files" or  "C:\Program Files(x86)" or maybe "C:\ProgramData", but never to the user data folder.

If a user (like me) has activated the default Windows Software Restriction Policy the install will fail, because it's not allowed to start programs from that location.

Please install to the default location for applications or let the user choose a destination folder. Thanks!

**Comment by thomasnordquist** [comment]
I do not agree, the app may be installed by any user.
Therefore the user has always write-permissions to the app.

Check out the release from the Microsoft Store
https://www.microsoft.com/en-us/p/mqtt-explorer/9pp8sfm082wd?activetab=pivot:overviewtab

Due to the build tools I use changing the installer is not trivial thing. You may also want to try the portable version.
