### ISSUE TITLE
Feature request: Sorting of topics

### ISSUE THREAD

**Issue by MaxVonEvil** [thomasnordquist/MQTT-Explorer#723]
Hi Thomas, first of thanks for an excellent project.

I was wondering if you might consider implementing an option to sort the topics in the left window. I have quite the number of Tasmota devices on my network and I adhere to a naming convention which would lend itself well to be sorted:

![image](https://user-images.githubusercontent.com/19863636/236639187-f18b5c92-b470-494a-8a6a-5fd8a2b8f34e.png)

Thanks!
//Max

**Comment by ilgrank** [comment]
In case you haven't noticed, the author is not developing this project since years... (just in case you expected a reply to your request)
________________________________
From: MaxVonEvil ***@***.***>
Sent: Saturday, May 6, 2023 5:47 PM
To: thomasnordquist/MQTT-Explorer ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [thomasnordquist/MQTT-Explorer] Feature request: Sorting of topics (Issue #723)


Hi Thomas, first of thanks for an excellent project.

I was wondering if you might consider implementing an option to sort the topics in the left window. I have quite the number of Tasmota devices on my network and I adhere to a naming convention which would lend itself well to be sorted:

[image]<https://user-images.githubusercontent.com/19863636/236639187-f18b5c92-b470-494a-8a6a-5fd8a2b8f34e.png>

Thanks!
//Max

**Comment by MaxVonEvil** [comment]
So it seems. I wonder if there's been any spin-off projects worth looking into?

**Comment by ilgrank** [comment]
The licence seems to prevend that alas

**Comment by MaxVonEvil** [comment]
D'oh, I just realized this feature can actually be found in the upper left menu..
