### ISSUE TITLE
MQTT broker: iot.eclipse.org moves to a new hostname

### ISSUE THREAD

**Issue by ralight** [thomasnordquist/MQTT-Explorer#74]
I've just discovered your tool via the ubuntu snap. I've not used it much yet, but the first impressions are very good.

I just wanted to make you aware that the iot.eclipse.org server is going to disappear or at least move at some point: https://bugs.eclipse.org/bugs/show_bug.cgi?id=541419

**Comment by thomasnordquist** [comment]
Thank you very much.
I'll watch this topic for updates.

**Comment by thomasnordquist** [comment]
Glad you like it 😊

**Comment by thomasnordquist** [comment]
Currently none of the default broker are online:
iot.eclipse.org and test.mosquitto.org do not seem to work with the app ATM.

`ral` from mqtt@irc.freenode.net mentioned that some clients mis-behave and try to reconnect mutliple times per second with the same client-id and that some clients have been blacklisted.
I should therefore evaluate the reconnect behavior (should be the default mqttjs behavior).

In order to maintain a up-to-date list of public brokers, the client should be able to update it's list from a curated list of brokers, so I can update the list of brokers without releasing a new version.

```
> nmap -p 1883 iot.eclipse.org
Starting Nmap 7.70 ( https://nmap.org ) at 2019-03-09 20:41 CET
Nmap scan report for iot.eclipse.org (198.41.30.241)
Host is up (0.14s latency).
rDNS record for 198.41.30.241: m2m.eclipse.org

PORT     STATE  SERVICE
1883/tcp closed mqtt
```

```
> nmap -p 1883 test.mosquitto.org
Starting Nmap 7.60 ( https://nmap.org ) at 2019-03-09 20:42 CET
Nmap scan report for test.mosquitto.org (37.187.106.16)
Host is up (0.025s latency).
Other addresses for test.mosquitto.org (not scanned): 2001:41d0:a:3a10::1
rDNS record for 37.187.106.16: ks.ral.me

PORT     STATE SERVICE
1883/tcp open  mqtt
```

```
mosquitto_pub -h test.mosquitto.org -p 1883 -t hello -m world
Error: The connection was lost.
```

**Comment by thomasnordquist** [comment]
I verified that at no time more than a single connection to a broker is created.
I connected to iot.eclipse.org and tested 
- network errors
- reconnects
- disconnect & connect
- and let it run for 2 days

There was at most a single TCP connection all this time.

Monitored connections with
```
while true; do netstat -p tcp | grep m2m.eclipse.org.ibm-mq; echo "End"; sleep 15; done;
```

**Comment by ralight** [comment]
The new hostname, which is live now, is `mqtt.eclipse.org`. Please change to using that.

**Comment by thomasnordquist** [comment]
Fixed with 7036d6c8fe9c714e4c40128dce0f620d8e3244b1
Thanks for reporting 😊

**Comment by Tommilein** [comment]
Hello,
I used iot.eclipse.org with web-sockets and javascript. But since some days I don't get a connect. It's normally, if you changed the URL.
But with "mqtt.eclipse.org" I don't get a connect also.

I use 2 Brokers and only one connected.

```
Try Connect_1 to: broker.mqttdashboard.com Port: 8000  Path: /mqtt 
Connect_1 to: broker.mqttdashboard.com Port: 8000 durchlaufen 

Try Connect_2 to: mqtt.eclipse.org Port: 80  Path: / 
Connect_2 to: mqtt.eclipse.org Port: 80 durchlaufen 

Connected 1: broker.mqttdashboard.com   // OK!!

Firefox kann keine Verbindung zu dem Server unter ws://mqtt.eclipse.org/ aufbauen. ```

I tried another Path:
**Firefox kann keine Verbindung zu dem Server unter ws://mqtt.eclipse.org/ws aufbauen.**

Connect failed to: >>> mqtt.eclipse.org <<<  Err: AMQJS0007E Socket error:undefined.
````
What is wrong? Port, Path ?? 

I hope you can help me.
Thank you
Thomas

**Comment by tylerkoldenjtp** [comment]
Thank you for creating this great tool, @thomasnordquist!

I attempted to use the default connection to mqtt.eclipseprojects.org, but it failed.  

![initial](https://user-images.githubusercontent.com/14161845/161383211-a8eccbee-bf13-4db5-bf97-0b57d919685d.png)

Based on [this page](https://iot.eclipse.org/projects/sandboxes/), I believe the new address should be **mqtt.eclipseprojects.io**.

![proposed](https://user-images.githubusercontent.com/14161845/161383219-0b618dcc-2e69-4d2d-a4b9-996ff1f948f0.png)

When I used **mqtt.eclipseprojects.io**, it worked as expected.

![connected](https://user-images.githubusercontent.com/14161845/161383228-787271ba-5ab3-4d24-bebf-0df4722e32d9.png)
