### ISSUE TITLE
Add graph for history of JSON values

### ISSUE THREAD

**Issue by tjorim** [thomasnordquist/MQTT-Explorer#77]
Similar to https://github.com/thomasnordquist/MQTT-Explorer/issues/31, but let users plot values in json topics as well; instead of only plotting numeric topics.

**Comment by thomasnordquist** [comment]
How would you go about it?

I thought about maybe shallow scan (first hierarchical level) of the json and plot those numbers.
One might also need to be able to select the plotted fields.

Axis scaling might be difficult:
A Unix timestamp is rather big compared to a temperature reading, plotting both and auto-scale the axis would make the temperature reading insignificant.

Few propositions:
- Add a "Plot" window that plots all values in their own graphs
- Add a combined plot but try to group/filter plots with similar magnitude
- Add a configuration for combined plots
- Add a configuration which field shall be used as time-base (instead of receive time)

**Comment by thomasnordquist** [comment]
Coming soon, current status as of 9e15e2814743859775a77be5638d42c0ef6d295d
<img width="909" alt="Bildschirmfoto 2019-06-04 um 22 00 30" src="https://user-images.githubusercontent.com/7721625/58909944-9cb95c80-8714-11e9-88ad-fb46100441c7.png">

**Comment by thomasnordquist** [comment]
By clicking on the Chart Icon, the chart will be added to a separate panel.

<img width="1440" alt="Bildschirmfoto 2019-06-16 um 20 17 44" src="https://user-images.githubusercontent.com/7721625/59568373-01ac7500-907a-11e9-8db9-ace867bff06e.png">

**Comment by thomasnordquist** [comment]
Released with [v0.3.5](https://github.com/thomasnordquist/MQTT-Explorer/releases/tag/v0.3.5).
