### ISSUE TITLE
Option to disable sparkplug autodecode.

### ISSUE THREAD

**Issue by plattrap** [thomasnordquist/MQTT-Explorer#808]
The sparkplug decoder has decided my JSON payload needs to be decoded and has hidden the actual payload data.

Real payload
```JSON
{
    "timestamp": "2024-06-03T10:58:51.882Z",
    "mac": "d97de462fc85",
    "stats_crc": "4b48",
    "anchor_stats": "1, 1, 1, 2, 1, 0, 0, 0",
    "history_stats": "8, 7, 9, 6, 6, 9, 5, 6"
}
```
Displayed payload ("Decoded SparkplugB")
```JSON
{
    "uuid": ", 0\", \"history_stats\": \"8, 7, 9, 6, 6, 9, 5, 6\"}"
}
```

**Comment by bj00rn** [comment]
@plattrap That uuid representation looks funky.. 

The same issue stands with `longs` etc. The get converterd in tp `{high: 12312, low: 2123123...`.

A limitation at the moment since the move from using Tahu instead of rolling our own sparkplug decoding using protobujs. I've opened an [issue](https://github.com/eclipse/tahu/issues/384) about this. Tahu does not seem to expose conversionOptions see [here](https://protobufjs.github.io/protobuf.js/Message.html#.toObject).

A workaround might be to add 'replacer's to JSON.stringify [here](https://github.com/thomasnordquist/MQTT-Explorer/blob/f539e03c7ebc44ab274159ba370b14fcd269b414/app/src/decoders/SparkplugBDecoder.ts#L15)
