### ISSUE TITLE
Fix settings propagation in tree

### ISSUE THREAD

**Issue by kloggy** [thomasnordquist/MQTT-Explorer#81]
I see that there was an issue that appeared to address (490678d, closed on 13 Jan) but I still see topics in a 'random' ordered list.

Thanks.

![image](https://user-images.githubusercontent.com/38220016/54747828-d1af1c00-4bc7-11e9-9b72-8ebc7761dc34.png)

![image](https://user-images.githubusercontent.com/38220016/54747861-e8ee0980-4bc7-11e9-895f-627d9a7a3b06.png)

**Comment by thomasnordquist** [comment]
Thanks for reporting 👍.
The problem here is that the new "topic order" is not immediately propagated to nested topics, only when a child topic receives an update.

Quick Fix:
Collapsing and expanding the "root" node (or simply reconnecting) will resolve this issue.

I'll keep you posted when it is fixed and when the fix has been released, there are also a few other things I'd like to put in the next release.

**Comment by kloggy** [comment]
That's great thanks. I was using MQTT.fx until I found this and I far prefer this!

**Comment by thomasnordquist** [comment]
Glad to hear it =)

**Comment by kloggy** [comment]
Although....
From this to this:
![image](https://user-images.githubusercontent.com/38220016/54748932-fbb60d80-4bca-11e9-8880-048dbb35e66b.png)

To this:
![image](https://user-images.githubusercontent.com/38220016/54748978-15efeb80-4bcb-11e9-8402-b19898ce34cc.png)

doesn't seem to re-sort. (Just so you know)

**Comment by thomasnordquist** [comment]
*Note to myself:* I also noticed this behavior for the "Quick Preview" option.
I should probably start using immutables ([immutablejs](https://github.com/immutable-js/immutable-js)) to guarantee the propagation of settings/values in the tree.

Directly connecting the nodes to the store is not possible since it would have a huge performance impact on every store update, even if store changes are unrelated to the topic. (10k nodes ~150ms)

**Comment by thomasnordquist** [comment]
Fixed with 436b569.
